### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by S1eepyBear** [visionspacetec/sle-provider#14]
what‘s the difference between sle-online and sle-offline mode？
We are currently testing with the ESA,but the offline mode can only bind,can't start.

**Comment by milenko-s** [comment]
Hi @fangcar 

In short, the `Online` modes are used during a pass over the ground station to communicate live with the spacecraft, while the `Offline` mode retrieves past data stored at the ground station.

There are three delivery modes in SLE (see https://public.ccsds.org/Pubs/911x1b5.pdf page 2-16 `2.6.4.6.2 Transfer Buffer` for an explanation of the differences.
- Timely online
- Complete online
- Offline

For the `Offline` mode, a database is required, and this is not implemented. We are supporting only `Timely Online` at the moment: https://github.com/visionspacetec/sle-provider/blob/d30fc258d52eed24b0d79f902253da191cdca00a/sleprovider/sleProvider.py#L146

**Comment by S1eepyBear** [comment]
Thank you for your answer,I have a general understanding for the two modes.

When I connect to a sle-provider,the config as follows. So the start_time/stop_time is not null, the delivery_mode is OFFLINE.Is there any other difference between online and offline mode?

`provider.si_config = {
    'sagr=1.spack=VST-PASS0001.rsl-fg=1.raf=onlt1':
        {
            'start_time': None,
            'stop_time': None,
            'initiator_id': 'SLE_USER',
            'responder_id': 'SLE_PROVIDER',
            'return_timeout_period': 15,
            'delivery_mode': 'TIMELY_ONLINE',
            'initiator': 'USER',
            'permitted_frame_quality':
                ['allFrames', 'erredFramesOnly', 'goodFramesOnly'],
            'latency_limit': 9,
            'transfer_buffer_size': 1,
            'report_cycle': None,
            'requested_frame_quality': 'allFrames',
            'state': 'unbound'
        }
}`

**Comment by milenko-s** [comment]
So `stop_time` must be earlier than the current time, `latency_limit` must be null, and you need to update the service instance identifier to end with `offlx` (e.g. `offl1` instead of the current `onlt1`).

But as explained, it is currently not implemented, so you must add some functionality. I would be happy to review if you open a merge request 👍

**Comment by S1eepyBear** [comment]
There is another question：
We received the SleBindReturn parameter,but it doesn't have the TML_SLE_TYPE(0x0100000000) header, the binary data is start with 0xbf65.
Is the reason of version？Or others？
