### ISSUE TITLE
'good' frames are not sent to user when requested_frame_quality is 'goodFramesOnly'

### ISSUE THREAD

**Issue by AdamElliott-AB** [visionspacetec/sle-provider#8]
https://github.com/visionspacetec/sle-provider/blob/2c3e34452adf608499527f79653a9fb0e3ca5d75/sleprovider/sleProvider.py#L150

**Comment by milenko-s** [comment]
Hello @AdamElliott-AB thank you for contributing to the project by reporting this bug! I tracked down the problem and will fix it soon. Please let us know afterwards if it works for you.

**Comment by AdamElliott-AB** [comment]
Thank you. Yes that fix works for me.

**Comment by milenko-s** [comment]
You are welcome! If you encounter any further problems feel free to open a new issue.
